"""Add amount_due to the Rental Model

Revision ID: 5a26af449df9
Revises: 716b23910f9a
Create Date: 2024-09-02 14:23:37.472971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a26af449df9'
down_revision = '716b23910f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('amount_due')

    # ### end Alembic commands ###
