"""empty message

Revision ID: 716b23910f9a
Revises: 
Create Date: 2024-08-31 17:19:37.751573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716b23910f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('student_id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_time', sa.DateTime(), nullable=False),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bicycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bicycle_id'], ['bicycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental')
    op.drop_table('user')
    op.drop_table('bicycle')
    # ### end Alembic commands ###
